import { Rubik } from 'next/font/google'
import '../globals.css'
import Providers from './Providers'
import { NextIntlClientProvider } from 'next-intl'
import { AuthProvider } from './AuthProvider'

const rubik = Rubik({
  variable: '--font-rubik',
  subsets: ['latin'],
  weight: ['300', '400', '500', '700', '900'],
  style: ['normal', 'italic'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full w-full">
      <body
        className={`${rubik.className} flex h-full w-full flex-col antialiased`}
      >
        <NextIntlClientProvider>
          <Providers>
            <AuthProvider>{children}</AuthProvider>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
